
package com.example.marketintelligence.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

// --- AI Engine Inputs & Outputs ---

enum class MarketRegime {
    TRENDING_BULLISH,
    TRENDING_BEARISH,
    RANGING_HIGH_VOLATILITY,
    RANGING_LOW_VOLATILITY,
    UNDEFINED
}

// Represents a complete, actionable trade signal generated by the AI
data class AiTradeSignal(
    val underlyingSymbol: String,
    val strategyName: String,
    val marketRegime: MarketRegime,
    val optionLegs: List<OptionLeg>,
    val entryPrice: Double, // Net premium
    val target: Double,
    val stopLoss: Double,
    val confidenceScore: Double,
    val riskParameters: RiskParameters
)

data class RiskParameters(
    val positionSize: Int, // Number of lots
    val capitalRequired: Double,
    val marginRequired: Double,
    val maxLoss: Double
)

// --- Persistence & Analytics ---

@Entity(tableName = "executed_trades")
data class ExecutedTradeEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val signal: AiTradeSignal,
    val outcome: String, // e.g., "TARGET_HIT", "STOP_LOSS_HIT", "CLOSED_MANUALLY"
    val closingPrice: Double,
    val profitAndLoss: Double,
    val executedAt: Long,
    val closedAt: Long
)
