package com.example.redxaiscanner.engine

import java.math.BigDecimal

/**
 * A lightweight, alert-ready event generated by the background scanner.
 * This contains the minimum information needed to create a user notification.
 *
 * @param symbol The market symbol where the setup was found.
 * @param direction The direction of the trade (BULLISH/BEARISH).
 * @param description A brief description of the setup (e.g., "Bullish Order Block @ 1H").
 * @param entryPrice The calculated entry price.
 * @param confidenceScore The final confidence score of the setup.
 */
data class AlertEvent(
    val symbol: String,
    val direction: MarketBias,
    val description: String,
    val entryPrice: BigDecimal,
    val confidenceScore: Int
)